openapi: 3.0.1
info:
  title: ArithmaticOperationServiceAPI
  description: API Definition of ArithmaticOperationServiceAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/arithmaticAPI
paths:
  /:
    post:
      responses:
        default:
          description: Default response
